# Generated by Django 2.2.19 on 2023-11-02 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_details', '0002_bankdetail_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0003_delete_requestfortransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bank_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_requests', to='bank_details.BankDetail')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_for_transaction', to='offers.Offer')),
            ],
            options={
                'unique_together': {('offer', 'applicant')},
            },
        ),
    ]
