# Generated by Django 2.2.19 on 2023-11-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_rub', models.FloatField(verbose_name='USD to RUB')),
                ('mnt_to_rub', models.FloatField(verbose_name='MNT to RUB')),
                ('mnt_to_usd', models.FloatField(verbose_name='MNT to USD')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
