# Generated by Django 2.2.19 on 2023-11-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='usd_to_rub_alternative',
            field=models.FloatField(default=1, verbose_name='USD to RUB (alternative)'),
            preserve_default=False,
        ),
    ]
