# Generated by Django 2.2.19 on 2023-08-10 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_offered', models.CharField(choices=[('USD', 'US Dollar'), ('RUB', 'Russian Ruble'), ('MNT', 'Mongolian Tugrik')], max_length=3)),
                ('amount_offered', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency_needed', models.CharField(choices=[('USD', 'US Dollar'), ('RUB', 'Russian Ruble'), ('MNT', 'Mongolian Tugrik')], max_length=3)),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=11)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
