# Generated by Django 2.2.19 on 2023-08-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_offered', models.CharField(choices=[('USD', 'US Dollar'), ('RUB', 'Russian Ruble'), ('MNT', 'Mongolian Tugrik')], max_length=3)),
                ('amount_offered', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency_needed', models.CharField(choices=[('USD', 'US Dollar'), ('RUB', 'Russian Ruble'), ('MNT', 'Mongolian Tugrik')], max_length=3)),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_asserts_transfer_done', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('author_uploads_transfer_screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('accepting_user_confirms_money_received', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('accepting_user_asserts_transfer_done', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('accepting_user_uploads_transfer_screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('author_money_confirms_received', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('status', models.CharField(choices=[('open', 'Transaction Opened'), ('in_progress', 'In Process'), ('closed', 'Closed'), ('dispute', 'Dispute Opened')], default='open', max_length=8)),
            ],
        ),
    ]
