# Generated by Django 2.2.19 on 2023-09-20 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accepting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='offers.Offer'),
        ),
        migrations.AddField(
            model_name='requestfortransaction',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestfortransaction',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_for_transaction', to='offers.Offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='requestfortransaction',
            unique_together={('offer', 'applicant')},
        ),
    ]
