# Generated by Django 2.2.19 on 2023-08-12 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_asserts_transfer_done', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('author_uploads_transfer_screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('accepting_user_confirms_money_received', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('accepting_user_asserts_transfer_done', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('accepting_user_uploads_transfer_screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('author_money_confirms_received', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('status', models.CharField(choices=[('open', 'Transaction Opened'), ('in_progress', 'In Process'), ('closed', 'Closed'), ('dispute', 'Dispute Opened')], default='open', max_length=8)),
                ('accepting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_transactions', to=settings.AUTH_USER_MODEL)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='offers.Offer')),
            ],
        ),
    ]
