# Generated by Django 2.2.19 on 2023-08-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20230814_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='author_money_confirms_received',
            new_name='author_confirms_money_received',
        ),
    ]
