# Generated by Django 2.2.19 on 2023-11-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20231102_0446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestForTransaction',
        ),
    ]
