# Generated by Django 2.2.19 on 2023-10-25 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231016_1039'),
        ('offers', '0002_auto_20231015_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfortransaction',
            name='bank_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_requests', to='users.BankDetail'),
        ),
    ]
