# Generated by Django 2.2.19 on 2023-08-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20230818_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=11),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('open', 'Transaction Opened'), ('in progress', 'In Process'), ('closed', 'Closed'), ('dispute', 'Dispute Opened')], default='open', max_length=8),
        ),
    ]
