# Generated by Django 2.2.19 on 2023-10-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='mnt_to_usd',
            field=models.FloatField(default=1, verbose_name='MNT to USD'),
            preserve_default=False,
        ),
    ]
