# Generated by Django 2.2.19 on 2023-11-02 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_exchangerate_mnt_to_usd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
