# Generated by Django 2.2.19 on 2023-11-02 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_delete_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='bank_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_offers', to='bank_details.BankDetail'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='currency_needed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_needed', to='bank_details.Currency'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='currency_offered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_offered', to='bank_details.Currency'),
        ),
        migrations.AlterField(
            model_name='requestfortransaction',
            name='bank_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_requests', to='bank_details.BankDetail'),
        ),
    ]
