# Generated by Django 2.2.19 on 2023-10-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankdetail',
            unique_together=set(),
        ),
    ]
