# Generated by Django 2.2.19 on 2023-11-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmation',
            name='confirmation_token',
        ),
        migrations.AddField(
            model_name='emailconfirmation',
            name='confirmation_code',
            field=models.CharField(default=1, editable=False, max_length=6),
            preserve_default=False,
        ),
    ]
