# Generated by Django 2.2.19 on 2023-08-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230815_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Unique referral code for the user.', max_length=255, null=True, unique=True),
        ),
    ]
