# Generated by Django 2.2.19 on 2023-10-09 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('USD', 'US Dollar'), ('RUB', 'Russian Ruble'), ('MNT', 'Mongolian Tugrik')], max_length=3, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('help_text_template', models.CharField(help_text="Template for the help text, e.g., 'Bank Name for {currency_name} transfers'", max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userfollow',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mnt_account_or_phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mnt_bank_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mnt_recipient_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rub_account_or_phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rub_bank_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rub_recipient_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='usd_account_or_phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='usd_bank_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='usd_recipient_name',
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_or_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'currency')},
            },
        ),
    ]
