# Generated by Django 2.2.19 on 2023-11-02 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231101_0643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
