# Generated by Django 2.2.19 on 2023-08-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invitation_code_used',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invites_left',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
