# Generated by Django 2.2.19 on 2023-11-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_asserts_transfer_done', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('author_uploads_transfer_screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('accepting_user_confirms_money_received', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('accepting_user_asserts_transfer_done', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('accepting_user_uploads_transfer_screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('author_confirms_money_received', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('status', models.CharField(choices=[('open', 'Transaction Opened'), ('in progress', 'In Process'), ('closed', 'Closed'), ('dispute', 'Dispute Opened')], default='open', max_length=8)),
            ],
        ),
    ]
