# Generated by Django 2.2.19 on 2023-11-02 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0002_auto_20231102_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accepting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='offers.Offer'),
        ),
    ]
