# Generated by Django 2.2.19 on 2024-04-26 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tic_tac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoegame',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
