# Generated by Django 2.2.19 on 2024-04-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac', '0003_auto_20240428_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='o_moves',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='game',
            name='x_moves',
            field=models.CharField(default='', max_length=9),
        ),
    ]
